# Creating a PersistentVolume that represents an EBS volume in AWS. The volume is configured with access mode ReadWriteOnce, a storage capacity of 20Gi, and it uses the EBS CSI driver to specify the volume handle and file system type.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-072a8f44214a23f64
---
# Creating a PersistentVolumeClaim to request storage from the previously created PersistentVolume. The claim specifies the desired storage size and access mode, and it will bind to the PersistentVolume that matches these requirements.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
# Creating a pod that uses the PersistentVolumeClaim to mount the EBS volume at /usr/share/nginx/html. The pod is scheduled to run on a specific node in the us-east-1c availability zone, and it runs an nginx container that serves content from the mounted volume.
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: ebs-static-demo
    project: roboshop
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  containers:
  - name: nginx
    image: nginx
    volumeMounts: # docker run -v host-path:container-path
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-static
---
# Creating a service to expose the nginx application on port 80, and it will route traffic to the pods with matching labels.
apiVersion: v1
kind: Service
metadata:
  name: ebs-static
  labels:
    purpose: ebs-static-demo
    project: roboshop
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-static-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port